name: GitHub Actions Demo
on:
  push:
    branches: [ "main" ]
    paths-ignore: [ ".github/workflows/*" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '15 6 * * 0'
  workflow_dispatch:
    inputs:
      environment:
        description: 'Env to deploy to'
        type: environment
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Output Values
      run: |
        echo "Triggering Event was ${{ github.event_name }}"
        echo "Current branch is ${{ github.ref }}"
        
    - uses: actions/checkout@v3.3.0

    - name: List files in the repository
      run: |
        echo "Repository ${{ github.repository }} has the files:"
        tree

  test:
    if: github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    needs: build
    environment: Test
    steps:
    - name: Testing
      run: echo "Testing..."
      
  load-test:
    if: github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: LoadTest
      run: |
        echo "Testing..."
        sleep 15

  production: 
    runs-on: ubuntu-latest
    needs: [test, load-test]
    environment:
      name: Production
      url: url: https://writeabout.net
    if: github.event.inputs.environment == 'Production'
    steps:
    - name: Step 1
      run: |
        echo "Step 1 deploying..."
        sleep 10
    - name: Step 2
      run: |
        echo "Step 2 deploying..."
        sleep 10
    - name: Step 3
      run: |
        echo "Step 3 deploying..."
        sleep 10
    - name: Step 4
      run: |
        echo "Step 5 deploying..."
        sleep 10
    - name: Step 1
      run: |
        echo "Step 5 deploying..."
        sleep 10
        
    
    
