name: GitHub Actions Demo
on:
  push:
    branches: [ "main" ]
    paths-ignore: [ ".github/workflows" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '15 6 * * 0'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Output Values
      run: |
        echo "Triggering Event was ${{ github.event_name }}"
        echo "Current branch is ${{ github.ref }}"
        
    - uses: actions/checkout@v3.3.0

    - name: List files in the repository
      run: |
        echo "Repository ${{ github.repository }} has the files:"
        tree
